name: CI

on: [push]

jobs:
  buildFrontend:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
    - name: Install frontend packages with NPM
      run: |
        export NVM_DIR=~/.nvm
        source ~/.nvm/nvm.sh   
        cd frontend/skinkis
        whoami
        pwd
        npm install
    - name: Build angular
      run: npm run-script ng build