name: CI

on: [push]

jobs:
  buildFrontend:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v1
    - name: Install frontend packages with NPM and build Angular
      run: |
        export NVM_DIR=~/.nvm
        source ~/.nvm/nvm.sh   
        cd frontend/skinkis
        whoami
        pwd
        npm install
        npm run-script ng build
        tree
    
    - name: Clean existing files from apache
      run: rm -rf /var/www/skinkis/*

    - name: Copy files to apache
      run: cp -r frontend/skinkis/dist/skinkis/browser/* /var/www/skinkis/

  buildBackend: 
    runs-on: self-hosted
    steps:
    - name: SKinkis
      run: pwd
      
