name: CI

on: [push]

jobs:
  buildFrontend:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v1
    - name: Install frontend packages with NPM and build Angular
      run: |
        export NVM_DIR=~/.nvm
        source ~/.nvm/nvm.sh   
        cd frontend/skinkis
        npm install
        npm run-script ng build
    
    - name: Clean existing files from apache
      run: rm -rf /var/www/skinkis/*

    - name: Copy files to apache
      run: cp -r frontend/skinkis/dist/skinkis/browser/* /var/www/skinkis/

  buildBackend: 
    runs-on: self-hosted
    steps:
    - name: Install packages and build backend
      run: |
        export NVM_DIR=~/.nvm
        source ~/.nvm/nvm.sh  
        cd backend/skinkis
        npm install
        npx tsc
        pwd
        ls -lah

    - name: Save .env!
      run: cp ~/skinkis/skinkisBackend/.env ~/skinkis/

    - name: Delete old files in running directory
      run: rm -rf ~/skinkis/skinkisBackend/*
    
    - name: Copy built files to running directory
      run: cp -r backend/skinkis/* ~/skinkis/skinkisBackend/

    - name: Save .env part 2!
      run: cp ~/skinkis/.env  ~/skinkis/skinkisBackend/

    - name: Restart PM2
      run: |
        export NVM_DIR=~/.nvm
        source ~/.nvm/nvm.sh  
        pm2 restart 0